[package]
name = "genatrix-connector-imap"
description = "Mail connector (IMAP and SMTP)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[[bin]]
name = "genatrix-imap"
path = "src/main.rs"

[dependencies]
genatrix-connector.workspace = true
genatrix-model.workspace = true
mail-parser = "0.11"
serde.workspace = true
thiserror.workspace = true
chrono.workspace = true
tracing.workspace = true
async-imap = "0.11"
async-native-tls = "0.6"
futures.workspace = true
tokio = { workspace = true }
tokio-util = { version = "0.7", features = ["compat"] }
clap = { workspace = true, features = ["derive"] }
serde_json.workspace = true
anyhow.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
