[package]
name = "genatrix-connector-imap"
description = "Mail connector (IMAP and SMTP)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[[bin]]
name = "genatrix-imap"
path = "src/main.rs"

[dependencies]

[lints]
workspace = true
