[package]
name = "genatrix-connector"
description = "Connector protocol and capabilities"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
genatrix-model.workspace = true
serde.workspace = true
thiserror.workspace = true
chrono.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
