[package]
name = "genatrix-connector"
description = "Connector protocol and capabilities"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
genatrix-model.workspace = true
serde.workspace = true
thiserror.workspace = true
chrono.workspace = true
prost = "0.13"
bytes.workspace = true
tokio = { workspace = true, features = ["net", "io-util", "rt", "macros", "sync"] }
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
